#Much of this is AI generated data
#This file only stores the riddles and quiz q/a s for the game



RIDDLES = [
    ("What has keys but can’t open locks?", {"piano", "keyboard"}),
    ("What has to be broken before you can use it?", {"egg"}),
    ("I’m tall when I’m young, and I’m short when I’m old. What am I?", {"candle"}),
    ("What is full of holes but still holds water?", {"sponge"}),
    ("What gets wet while drying?", {"towel"}),
    ("What can you catch, but not throw?", {"cold"}),
    ("What goes up but never comes down?", {"age"}),
    ("I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", {"echo"}),
    ("What has a head, a tail, is brown, and has no legs?", {"penny"}),
    ("What runs all around a backyard, yet never moves?", {"fence"}),
    ("What has keys but can’t open locks?", {"piano", "keyboard", "instrument"}),
    ("I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", {"echo", "sound", "voice"}),
    ("The more you take, the more you leave behind. What am I?", {"footsteps", "tracks", "marks"}),
    ("What has hands but can’t clap?", {"clock", "watch", "time"}),
    ("I’m tall when I’m young, and I’m short when I’m old. What am I?", {"candle", "light", "wax"}),
    ("What can travel around the world while staying in a corner?", {"stamp", "postage", "corner"}),
    ("What has to be broken before you can use it?", {"egg", "shell", "break"}),
    ("I’m not alive, but I grow; I don’t have lungs, but I need air; I don’t have a mouth, but water kills me. What am I?", {"fire", "flame", "heat"}),
    ("What gets wetter as it dries?", {"towel", "cloth", "dry"}),
    ("What has a head, a tail, is brown, and has no legs?", {"penny", "coin", "money"}),
    ("What has many teeth but can’t bite?", {"comb", "toothbrush", "hair"}),
    ("What is full of holes but still holds water?", {"sponge", "cloth", "cleaning"}),
    ("I’m not alive, but I can grow; I don’t have lungs, but I need air; I don’t have a mouth, but water kills me. What am I?", {"fire", "flame", "burn"}),
    ("What comes once in a minute, twice in a moment, but never in a thousand years?", {"letter M", "alphabet", "time"}),
    ("What has a neck but no head?", {"bottle", "jar", "container"}),
    ("What can you catch but not throw?", {"cold", "illness", "sickness"}),
    ("What has one eye but can’t see?", {"needle", "storm", "hole"}),
    ("What has a bed but doesn’t sleep, and a mouth but doesn’t eat?", {"river", "stream", "water"}),
    ("What has cities, but no houses; forests, but no trees; and rivers, but no water?", {"map", "atlas", "diagram"}),
    ("What has a thumb and four fingers but is not alive?", {"glove", "handwear", "clothing"}),
    ("What can be cracked, made, told, and played?", {"joke", "story", "game"}),
    ("What is so fragile that saying its name breaks it?", {"silence", "quiet", "sound"}),
    ("I have keys but open no locks. I have space but no room. You can enter but not go outside. What am I?", {"keyboard", "computer", "typewriter"}),
    ("What has a face and two hands but no arms or legs?", {"clock", "watch", "timepiece"}),
    ("What has an eye but cannot see, and is commonly found on a farm?", {"needle", "corn", "eye"}),
    ("What has a beginning but no end, and can be seen every day but never touched?", {"sunrise", "time", "day"}),
    ("I am not alive, but I can grow; I don’t have lungs, but I need air; I don’t have a mouth, but I need water. What am I?", {"fire", "flame", "heat"}),
    ("What gets bigger the more you take away from it?", {"hole", "gap", "space"}),
    ("What has a bottom at the top?", {"leg", "bed", "furniture"}),
    ("What can fill a room but takes up no space?", {"light", "air", "sound"}),
    ("What can be broken but never held?", {"promise", "trust", "agreement"}),
    ("What has a heart that doesn’t beat?", {"artichoke", "vegetable", "plant"}),
    ("What is always in front of you but can’t be seen?", {"future", "air", "time"}),
    ("What has a face and two hands but no body?", {"clock", "watch", "timepiece"}),
    ("What is full of keys but can’t open any doors?", {"piano", "keyboard", "instrument"}),
    ("What can travel around the world while staying in a corner?", {"stamp", "postage", "letter"}),
    ("What has a bottom at the top?", {"leg", "bed", "furniture"}),
    ("What is always in front of you but can’t be seen?", {"future", "air", "time"}),
    ("What gets wetter as it dries?", {"towel", "cloth", "dry"}),
    ("What can be cracked, made, told, and played?", {"joke", "story", "game"}),
    ("What has to be broken before you can use it?", {"egg", "shell", "break"}),
    ("What is so fragile that saying its name breaks it?", {"silence", "quiet", "sound"}),
    ("What has many teeth but can’t bite?", {"comb", "toothbrush", "hair"}),
    ("What has an eye but cannot see, and is commonly found on a farm?", {"needle", "corn", "eye"}),
    ("What has a bed but doesn’t sleep, and a mouth but doesn’t eat?", {"river", "stream", "water"}),
    ("What can you catch but not throw?", {"cold", "illness", "sickness"}),
    ("What is always in front of you but can’t be seen?", {"future", "air", "time"}),
    ("What can be cracked, made, told, and played?", {"joke", "story", "game"}),
    ("What has a thumb and four fingers but is not alive?", {"glove", "handwear", "clothing"}),
    ("What has a bed but doesn’t sleep, and a mouth but doesn’t eat?", {"river", "stream", "water"})
]


MYTHOLOGY_QUESTIONS = [
    ("Who is the king of the Greek gods?", ["Zeus", "Hades", "Poseidon", "Apollo"]),
    ("What is Thor’s hammer called in Norse mythology?", ["Mjolnir", "Gungnir", "Gram", "Skofnung"]),
    ("Who is the Roman god of war?", ["Mars", "Jupiter", "Neptune", "Mercury"]),
    ("In Egyptian mythology, who is the god of the underworld?", ["Osiris", "Ra", "Horus", "Anubis"]),
    ("Who was the Greek goddess of wisdom?", ["Athena", "Hera", "Aphrodite", "Demeter"]),
    ("What creature has the body of a lion and the head of a human in Egyptian mythology?", ["Sphinx", "Minotaur", "Chimera", "Griffin"]),
    ("In Greek mythology, who flew too close to the sun?", ["Icarus", "Daedalus", "Perseus", "Orpheus"]),
    ("Which Norse god is known as the trickster?", ["Loki", "Odin", "Thor", "Frey"]),
    ("Who is the Greek god of the sea?", ["Poseidon", "Zeus", "Hades", "Hermes"]),
    ("What is the Roman name for the Greek god Hermes?", ["Mercury", "Apollo", "Juno", "Vulcan"]),
    ("Who is the Norse god of thunder?", ["Thor", "Loki", "Odin", "Baldur"]),
    ("In Greek mythology, who was condemned to hold up the sky for eternity?", ["Atlas", "Prometheus", "Hermes", "Zeus"]),
    ("Who is the goddess of love and beauty in Roman mythology?", ["Venus", "Diana", "Minerva", "Juno"]),
    ("What is the name of the Greek goddess of the hunt?", ["Artemis", "Athena", "Hera", "Aphrodite"]),
    ("In Norse mythology, what is the name of the world tree?", ["Yggdrasil", "Asgard", "Midgard", "Jotunheim"]),
    ("Who is the Greek god of wine?", ["Dionysus", "Apollo", "Hermes", "Ares"]),
    ("What is the name of the Egyptian sun god?", ["Ra", "Osiris", "Anubis", "Horus"]),
    ("In Greek mythology, who is the god of the underworld?", ["Hades", "Zeus", "Poseidon", "Ares"]),
    ("Who is the king of the Norse gods?", ["Odin", "Thor", "Loki", "Tyr"]),
    ("In Roman mythology, who is the queen of the gods?", ["Juno", "Venus", "Minerva", "Ceres"]),
    ("Who is the goddess of the hearth in Greek mythology?", ["Hestia", "Hera", "Demeter", "Athena"]),
    ("What creature is half-man and half-horse in Greek mythology?", ["Centaur", "Minotaur", "Satyr", "Griffin"]),
    ("In Greek mythology, who is the messenger of the gods?", ["Hermes", "Apollo", "Athena", "Ares"]),
    ("What is the name of Thor’s father in Norse mythology?", ["Odin", "Loki", "Baldur", "Heimdall"]),
    ("Who is the goddess of the harvest in Greek mythology?", ["Demeter", "Hestia", "Artemis", "Hera"]),
    ("In Roman mythology, who is the god of the sea?", ["Neptune", "Mars", "Jupiter", "Vulcan"]),
    ("Who was the first woman created by the gods in Greek mythology?", ["Pandora", "Eurydice", "Helen", "Medusa"]),
    ("What is the name of the fire-breathing creature with the head of a lion, body of a goat, and tail of a serpent?", ["Chimera", "Cerberus", "Hydra", "Minotaur"]),
    ("Who is the Norse goddess of love and fertility?", ["Freyja", "Frigg", "Skadi", "Hel"]),
    ("In Greek mythology, who is known as the god of war?", ["Ares", "Apollo", "Zeus", "Hermes"]),
    ("What is the name of the three-headed dog that guards the underworld in Greek mythology?", ["Cerberus", "Hydra", "Chimera", "Sphinx"]),
    ("In Egyptian mythology, who is the goddess of magic?", ["Isis", "Bastet", "Nut", "Nephthys"]),
    ("Who is the Greek god of music, poetry, and the sun?", ["Apollo", "Hermes", "Dionysus", "Ares"]),
    ("What creature in Greek mythology turns people to stone with its gaze?", ["Medusa", "Siren", "Harpy", "Gorgon"]),
    ("In Norse mythology, what is the name of the hall where warriors go after death?", ["Valhalla", "Asgard", "Midgard", "Helheim"]),
    ("Who is the goddess of the moon in Greek mythology?", ["Selene", "Hecate", "Nyx", "Artemis"]),
    ("In Roman mythology, who is the god of the forge?", ["Vulcan", "Mars", "Neptune", "Apollo"]),
    ("Who is the Greek goddess of the harvest and agriculture?", ["Demeter", "Hera", "Athena", "Artemis"]),
    ("What is the name of the river that souls must cross to enter the underworld in Greek mythology?", ["Styx", "Lethe", "Acheron", "Phlegethon"]),
    ("Who is the Egyptian goddess of the sky?", ["Nut", "Isis", "Ma'at", "Hathor"]),
    ("In Greek mythology, who was cursed to turn everything he touched into gold?", ["King Midas", "Sisyphus", "Orpheus", "Perseus"]),
    ("Who is the Roman goddess of the hunt?", ["Diana", "Minerva", "Vesta", "Venus"]),
    ("In Norse mythology, who is the wife of Odin?", ["Frigg", "Freyja", "Hel", "Skadi"]),
    ("Who is the Greek god of the underworld?", ["Hades", "Zeus", "Poseidon", "Apollo"]),
    ("What is the name of the winged horse in Greek mythology?", ["Pegasus", "Chimera", "Hydra", "Griffin"]),
    ("In Egyptian mythology, who is the god of the sun?", ["Ra", "Osiris", "Horus", "Anubis"]),
    ("Who is the Norse god of wisdom, poetry, and magic?", ["Odin", "Thor", "Loki", "Baldur"]),
    ("In Greek mythology, who is the god of sleep?", ["Hypnos", "Morpheus", "Thanatos", "Erebus"]),
    ("What is the name of the goddess of discord in Greek mythology?", ["Eris", "Nemesis", "Ate", "Hecate"]),
    ("In Roman mythology, who is the god of wine?", ["Bacchus", "Jupiter", "Mars", "Apollo"]),
    ("Who is the Greek god of love?", ["Eros", "Hermes", "Apollo", "Ares"]),
    ("What creature in Greek mythology is known for its beautiful singing that lures sailors to their doom?", ["Siren", "Harpy", "Gorgon", "Nymph"]),
    ("Who is the Roman goddess of love?", ["Venus", "Juno", "Diana", "Minerva"]),
    ("In Norse mythology, who is the god of light and purity?", ["Baldur", "Thor", "Loki", "Odin"]),
    ("Who is the Greek god of the sun?", ["Helios", "Apollo", "Hermes", "Ares"]),
    ("What is the name of the giant serpent in Norse mythology that encircles the world?", ["Jörmungandr", "Fafnir", "Nidhogg", "Fenrir"]),
    ("In Egyptian mythology, who is the goddess of the home and fertility?", ["Hathor", "Bastet", "Isis", "Nephthys"]),
    ("Who is the king of the Titans in Greek mythology?", ["Cronus", "Atlas", "Prometheus", "Hyperion"]),
    ("What creature in Greek mythology is part woman and part bird?", ["Harpy", "Siren", "Gorgon", "Sphinx"]),
    ("Who is the Roman god of the underworld?", ["Pluto", "Mars", "Neptune", "Vulcan"]),
    ("In Norse mythology, what is the name of the wolf destined to kill Odin?", ["Fenrir", "Garm", "Skoll", "Hati"]),
    ("Who is the Greek goddess of victory?", ["Nike", "Athena", "Hera", "Artemis"]),
    ("In Roman mythology, who is the god of beginnings and endings?", ["Janus", "Jupiter", "Mars", "Vulcan"]),
    ("Who is the Greek goddess of the hearth and home?", ["Hestia", "Hera", "Demeter", "Artemis"]),
    ("What is the name of the nine-headed serpent in Greek mythology?", ["Hydra", "Cerberus", "Chimera", "Sphinx"]),
    ("In Egyptian mythology, who is the god of chaos and storms?", ["Set", "Anubis", "Ra", "Thoth"]),
    ("Who is the Norse god of fertility and prosperity?", ["Frey", "Tyr", "Baldur", "Odin"]),
    ("Who is the Greek god of healing and medicine?", ["Asclepius", "Apollo", "Hermes", "Dionysus"]),
    ("What is the name of the messenger of the gods in Roman mythology?", ["Mercury", "Apollo", "Mars", "Neptune"]),
    ("In Greek mythology, who is the goddess of the night?", ["Nyx", "Selene", "Hecate", "Eris"]),
    ("Who is the Roman god of fire and blacksmiths?", ["Vulcan", "Mars", "Neptune", "Mercury"]),
    ("In Norse mythology, who is the ruler of the underworld?", ["Hel", "Loki", "Fenrir", "Odin"]),
    ("Who is the Greek goddess of magic?", ["Hecate", "Eris", "Nyx", "Selene"]),
    ("What creature in Greek mythology is a woman with snakes for hair?", ["Medusa", "Siren", "Harpy", "Sphinx"]),
    ("In Roman mythology, who is the god of agriculture?", ["Saturn", "Mars", "Vulcan", "Mercury"]),
    ("Who is the Egyptian goddess of motherhood and fertility?", ["Isis", "Hathor", "Bastet", "Nut"]),
    ("In Norse mythology, who is the god of war and justice?", ["Tyr", "Thor", "Odin", "Loki"]),
    ("Who is the Greek goddess of the moon and hunting?", ["Artemis", "Hera", "Athena", "Demeter"]),
    ("What is the name of the primordial void in Greek mythology?", ["Chaos", "Gaia", "Tartarus", "Erebus"]),
    ("In Roman mythology, who is the goddess of wisdom and war?", ["Minerva", "Juno", "Diana", "Venus"]),
    ("Who is the Greek god of the sky?", ["Zeus", "Poseidon", "Hades", "Apollo"]),
    ("What is the name of the horse that has wings in Greek mythology?", ["Pegasus", "Chimera", "Cerberus", "Hydra"]),
    ("In Egyptian mythology, who is the god of wisdom and writing?", ["Thoth", "Anubis", "Ra", "Horus"]),
    ("Who is the Norse god of mischief?", ["Loki", "Thor", "Odin", "Tyr"]),
    ("Who is the Greek goddess of the earth?", ["Gaia", "Hera", "Demeter", "Artemis"]),
    ("In Roman mythology, who is the god of the underworld?", ["Pluto", "Mars", "Neptune", "Vulcan"]),
    ("Who is the Norse goddess of love, beauty, and fertility?", ["Freyja", "Frigg", "Hel", "Skadi"]),
    ("In Greek mythology, who is the god of fire and blacksmiths?", ["Hephaestus", "Apollo", "Ares", "Hermes"]),
    ("What is the name of the river that separates the world of the living from the world of the dead in Greek mythology?", ["Styx", "Lethe", "Acheron", "Phlegethon"]),
    ("Who is the Roman goddess of the hearth?", ["Vesta", "Minerva", "Venus", "Juno"]),
    ("In Norse mythology, who is the god of the sea?", ["Njord", "Thor", "Odin", "Loki"]),
    ("Who is the Greek goddess of the rainbow?", ["Iris", "Hera", "Artemis", "Demeter"]),
    ("What is the name of the ferryman who carries souls across the river Styx in Greek mythology?", ["Charon", "Cerberus", "Hades", "Hermes"]),
    ("In Egyptian mythology, who is the goddess of cats?", ["Bastet", "Hathor", "Isis", "Nut"]),
    ("Who is the Greek god of dreams?", ["Morpheus", "Hypnos", "Thanatos", "Phobos"]),
    ("In Norse mythology, what is the name of the realm of fire?", ["Muspelheim", "Asgard", "Midgard", "Helheim"]),
]

LOGIC_PUZZLES = [
    ("Which number should come next in the pattern: 2, 4, 8, 16, ...?", ["32", "20", "24", "30"]),
    ("If you rearrange the letters 'CIFAIPC', you would have the name of a(n):", ["Ocean", "City", "Animal", "Country"]),
    ("What is the missing number in the sequence: 1, 3, 6, 10, 15, ...?", ["21", "18", "20", "22"]),
    ("Which word does not belong in the following list: Apple, Banana, Cherry, Carrot?", ["Carrot", "Banana", "Apple", "Cherry"]),
    ("If some cats are lions and some lions are tigers, are some cats definitely tigers?", ["No", "Yes", "Cannot be determined", "Sometimes"]),
    ("John is standing behind Mary, and Mary is standing behind John. How is this possible?", ["They are standing back-to-back", "John is taller", "Mary is shorter", "They are in a line"]),
    ("If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?", ["5 minutes", "100 minutes", "50 minutes", "10 minutes"]),
    ("How many sides does a cube have?", ["6", "8", "4", "12"]),
    ("Which one of the following is the odd one out: 2, 3, 5, 7, 9?", ["9", "3", "5", "7"]),
    ("A clock shows the time as 3:15. What is the angle between the hour and minute hand?", ["7.5 degrees", "0 degrees", "15 degrees", "90 degrees"]),
    ("A bat and a ball cost $1.10 in total. The bat costs $1 more than the ball. How much does the ball cost?", ["5 cents", "10 cents", "15 cents", "1 cent"]),
    ("If it takes 12 men 12 hours to build a wall, how long would it take 6 men to build the same wall?", ["12 hours", "6 hours", "24 hours", "18 hours"]),
    ("If you have a 5-liter jug and a 3-liter jug, how can you measure exactly 4 liters of water?", ["Fill the 5-liter jug, pour into the 3-liter jug twice", "Fill the 3-liter jug twice", "Fill the 5-liter jug once", "Fill the 3-liter jug once"]),
    ("In a race, you overtake the person in second place. What position are you now in?", ["Second", "First", "Third", "Last"]),
    ("A farmer has 17 sheep, and all but 9 die. How many sheep does the farmer have left?", ["9", "8", "0", "17"]),
    ("What can travel around the world while staying in the same spot?", ["A stamp", "The wind", "A satellite", "A cloud"]),
    ("How many months have 28 days?", ["All of them", "1", "12", "6"]),
    ("I am an odd number. Take away one letter, and I become even. What number am I?", ["Seven", "Eleven", "Nine", "Three"]),
    ("You see a boat filled with people. It has not sunk, but when you look again you don’t see a single person. Why?", ["All the people were married", "The boat left", "The people jumped", "The boat capsized"]),
    ("What comes next in the sequence: 1, 1, 2, 3, 5, 8, ...?", ["13", "10", "12", "15"]),
    ("What is the next number in the series: 5, 10, 20, 40, ...?", ["80", "60", "100", "70"]),
    ("If A is the father of B and C is the mother of B, what is the relationship of A to C?", ["Husband", "Brother", "Uncle", "Cousin"]),
    ("In a race, you overtake the person in second place. What position are you in?", ["Second", "First", "Third", "Fourth"]),
    ("Which one of the following is a prime number?", ["17", "18", "20", "22"]),
    ("Which of the following does not belong in this group: Dog, Cat, Hamster, Whale?", ["Whale", "Dog", "Cat", "Hamster"]),
    ("If you have 3 apples and you take away 2, how many do you have?", ["2", "1", "0", "3"]),
    ("If you multiply a number by 6 and then add 2, you get 20. What is the number?", ["3", "4", "2", "5"]),
    ("Which number is missing from the sequence: 2, 3, 5, 7, 11, ...?", ["13", "9", "15", "17"]),
    ("What letter comes next in the sequence: J, F, M, A, M, ...?", ["J", "A", "M", "J"]),
    ("What number comes next: 1, 4, 9, 16, 25, ...?", ["36", "30", "32", "40"]),
    ("If all bloogs are shmoogs and all shmoogs are kroogs, are all bloogs definitely kroogs?", ["Yes", "No", "Cannot be determined", "Sometimes"]),
    ("What is the odd one out: Fork, Spoon, Knife, Plate?", ["Plate", "Fork", "Spoon", "Knife"]),
    ("A man is looking at a picture of someone. His friend asks, 'Who is it you are looking at?' The man replies, 'Brothers and sisters, I have none. But that man's father is my father's son.' Who is the man in the picture?", ["His son", "His father", "His uncle", "His nephew"]),
    ("A farmer has 17 sheep and all but 9 die. How many are left?", ["9", "8", "0", "17"]),
    ("Which word is closest in meaning to 'opaque'?", ["Cloudy", "Clear", "Bright", "Transparent"]),
    ("Which of the following numbers is a multiple of 3?", ["15", "14", "10", "25"]),
    ("If 3 people can paint 3 fences in 3 hours, how many fences can 6 people paint in 6 hours?", ["12", "9", "6", "3"]),
    ("What number is missing: 7, 14, 21, ..., 35?", ["28", "24", "30", "27"])
]
