"""
Code by Arush Mundada

Disclaimer:
Some stuff was generated by AI, those parts have #AI Generated Start and #AI Generated End before and after them

Users will be given the option to provide an OpenAI API key to create a more imersive experience (optional always)
"""

print("""
Welcome to the Text Based Adventure!

Some tips:
Come back every once in a while to see if there are any new updates!
Enter quit to exit the game.
Enter save to save your progress in the game to a file (you will need to enter a filename).
Enter autosave to automatically save the game whenever possible.
      
If you see a "..." click enter to continue
      
Try it out...""")
input()
print("Great! Let's get started!")

from random import choice as randchoice
from time import sleep
import os.path

WPM = 500 #Words per minute for the text animation, 1 word = 6 characters including spaces and special characters, neglecting time for print statement
DISABLE_ANIMATION = True
OPENAI_API_KEY = None #Optional, if not provided make it be None, else a string with the key

if OPENAI_API_KEY != None:
    import openai

    def get_openai_response(prompt):
        response = openai.Completion.create(
            engine="gpt4",
            prompt=prompt,
            max_tokens=300
        )
        return response.choices[0].text.strip()

else:
    def get_openai_response(prompt):
        return "Roses are red, Violets are blue, to get a better response, provide an OpenAI API key too!"


def char_animation(msg, end = "\n"):
    for char in msg:
        print(char, end = "", flush = True)
        sleep(10/WPM)
    print(end, end = "")

def char_animation_in(msg):
    char_animation(msg, end = "")
    return input()

if DISABLE_ANIMATION:
    char_animation = print
    char_animation_in = input

def get_char_animation_in(msg,accepted, allow_save = False,err_msg = ""): #{'choice1':['choice1','alias1','alias2'],'choice2':['choice2','alias1','alias2']}
    while True:
        choice = char_animation_in(msg).lower()
        if choice == 'quit':
            a = char_animation_in("Are you sure? If you haven't saved your progress, you will lose it. Press enter to confirm, or anything else to cancel. You can enter 'save' to save")
            if a == '':
                exit()
        elif choice == 'save' or (autosave and allow_save):
            if not allow_save:
                char_animation("You can't save right now :(\nPlease wait till you are prompted which place to go next!")
                continue
            if autosave:
                filename = "game.data"
            else:
                filename = char_animation_in("Enter a filename: ")
            with open(filename, 'w') as f:
                f.write(f"{situtation}\n{NAME}\n{been_in_situations}\n{morailty}\n{person_type}\n{career}\n{previous_choices}\n{gold}\n{inventory}\n{autosave}")

        for key in accepted:
            if choice in [item.lower() for item in accepted[key]]:
                return key
        char_animation(err_msg, end = "")

def get_karma(thing):
    try:
        return previous_choices[thing]
    except KeyError:
        return 0

situtation = 0
been_in_situations = set()
morailty = 0
NAME = "person"
person_type = 0
career = None
previous_choices = {}
gold = 0
inventory = {}
autosave = False
#Constants
WIZARD = "Wizard"
WARRIOR = "Warrior"
VILLIAN = "Villian"
WARLOCK = "Warlock"
GHOST = "Ghost"

#AI GENERATED START
RIDDLES = {
    'What has keys but can’t open locks?': {'piano', 'keyboard'},
    'What has to be broken before you can use it?': {'egg'},
    'I’m tall when I’m young, and I’m short when I’m old. What am I?': {'candle'},
    'What is full of holes but still holds water?': {'sponge'},
    'What gets wet while drying?': {'towel'},
    'What can you catch, but not throw?': {'cold'},
    'What goes up but never comes down?': {'age'},
    'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?': {'echo'},
    'What has a head, a tail, is brown, and has no legs?': {'penny'},
    'What runs all around a backyard, yet never moves?': {'fence'}
}
#AI GENERATED END


while True:
    if career == None: #Standard Careers (not including ghost)
        if abs(morailty) >= 5 and abs(person_type) >= 5:
            if morailty >= 5 and person_type >= 5:
                career = WIZARD
            elif morailty >= 5 and person_type <= -5:
                career = WARRIOR
            elif morailty <= -5 and person_type >= 5:
                career = VILLIAN
            elif morailty <= -5 and person_type <= -5:
                career = WARLOCK

    if situtation == 0:
        char_animation("Welcome Adventurer!")
        char_animation("1) Start a new game")
        char_animation("2) Load a game")

        if os.path.exists("game.data"):
            char_animation("3) Continue from save detected in game.data")
            choice = get_char_animation_in("Enter your choice: ",{'a':['1','start','new'],'b':['2','load'],'c':['3','game']}, "")
        else:
            choice = get_char_animation_in("Enter your choice: ",{'a':['1','start','new'],'b':['2','load']}, "")

        if choice == 'a':
            situtation = 1
        elif choice == 'b' or choice == 'c':
            if choice == 'b':
                filename = char_animation_in("Enter a filename: ")
            else:
                filename = "game.data"
            with open(filename) as file:
                save_data = file.read().split('\n')
                situtation = int(save_data[0])
                NAME = save_data[1]
                been_in_situations = {int(item) for item in save_data[2].strip('{}').split(',')}
                morailty = int(save_data[3])
                person_type = int(save_data[4])
                career = save_data[5]
                previous_choices = {int(item) for item in save_data[6].strip('{}').split(',')}
                gold = int(save_data[7])
                inventory = {int(item) for item in save_data[8].strip('{}').split(',')}
                autosave = save_data[9] == 'True'
        situtation = 1
    
    elif situtation == 1: #Clearing
        if 1 not in been_in_situations:
            char_animation("You wake up in the clearing of a forest, not remembering how you got here. You don't remember anything or anyone. The only thing you remember is a single word: your name.")
            NAME = char_animation_in("What is it?: ")
            been_in_situations.add(1)
        char_animation(f"Hello {NAME}. You see 4 paths labeled with signs: ")

        char_animation("\n\n")
        char_animation("1. The path going to the Temple, it has a a bricked road with lamps on the side.")
        char_animation("2. The path going to the Library, it has a road covered with leaves, seemingly not being disturbed in years.")
        char_animation("3. The path to the Arena, it has a road with a lot of footchar_animations, and you can hear the sound of swords clashing from the distance.")                    
        char_animation("4 The path to the Dragon's lair, the sign itself tangled with vines and the path so overgrown it may as well not have been there.")
        choice = get_char_animation_in("Which path do you take?: ",{'2':['1','temple'],'3':['2','library'],'4':['3','arena'],'5':['4',"dragon","lair"]}, allow_save=True)
        situtation = int(choice)

    elif situtation == 2: #Temple
        char_animation("\n\nTemple")
        if 2 not in been_in_situations:
            char_animation("As you walk down this path you see another person walking down the path. Do you?: ")
            char_animation("1. Ask him for help")
            char_animation("2. Ignore him")
            char_animation("3. Attack him")
            choice = get_char_animation_in("Enter your choice: ",{'a':['1','ask','help'],'b':['2','ignore'],'c':['3','attack']})
            if choice == 'a':
                previous_choices["old man"] = 1
                person_type += 1
                morailty += 1
                char_animation("You ask him for help, and he says: ")
                char_animation("What do you mean you don't know where you are?! You are in the kingdom of Mythopes, ruled by Emporer Rahas! Child you look like you need help, I am old I don't have much but you can have this: +100 Gold")
            elif choice == 'b':
                previous_choices["old man"] = 0
                person_type -= 1
                char_animation("You ignore him and continue down the path... On your way there you see a bag of gold on the side of the path, you could've sworn it wasn't there a moment ago, +100 Gold")
            elif choice == 'c':
                previous_choices["old man"] = -1
                person_type -= 1
                morailty -= 10000
                char_animation("You quickly overpower him, +100 Gold")

            char_animation("You continue down the path and you see a temple, and you enter it. There are a few people inside who seem to put money into the temple's donation box. Do you: ")
            char_animation("1. Put some money in the donation box")
            char_animation("2. Ignore the donation box")
            choice = get_char_animation_in("Enter your choice: ",{'a':['1','put','money'],'b':['2','ignore']})
            if choice == 'a':
                amt = int(char_animation_in("How much money do you put in the donation box?: "))
                previous_choices["donation"] = amt
                gold -= amt
                if amt > 0:
                    char_animation(f"You put the {amt} money in the donation box")
                if gold < 0:
                    char_animation("You are now in debt but you feel good :)")
                    morailty += 1000
                if amt > 50:
                    morailty += 2
                if amt > 80:
                    morailty += 1
                if morailty == 100:
                    morailty += 2
                if amt < 0:
                    char_animation(f"You take the {amt} money from the donation box", end="")
                    char_animation(f".{' '*150}.{' '*150}.{' '*150}\nYou suddenly feel a sharp pain in you head. You hear a nasty voice in your head 'hahaha you think you can fool me!!'")
                    char_animation(f"Do you wish to explain yourself? (yes/no)")
                    choice = get_char_animation_in("Enter your choice: ",{'a':['1','yes','explain', 'y'],'b':['2','no','ignore', 'n']})
                    if choice == 'a':
                        the_explanation = char_animation_in("[Explain youself]: ").lower()
                        if 'sorry' in the_explanation:
                            the_explanation = the_explanation.split('sorry')
                            the_explanation = the_explanation[0].split('not')
                            if len(the_explanation)%2 == 0:
                                char_animation("Intersting explanation, *not* an apology though.")
                            else:
                                char_animation("You explain yourself... ")
                                char_animation("The voice in your head says 'I will let you go this time... if you solve my riddle'")
                                riddle = randchoice(list(RIDDLES.keys()))
                                char_animation("    " + riddle)
                                ans = char_animation_in("Answer: ").lower()
                                if ans in RIDDLES[riddle]:
                                    char_animation("You are correct... surprising for a mortal... to bad you still have to go")
                                else:
                                    char_animation("You're wrong... bye!")
                        else:
                            char_animation("You don't even say sorry... some apology!")
                    char_animation("The sharp pain in your head multiplies hundred fold and you die... no worse... you are neither here nor there, you are a ghost.")
                    career = GHOST
            if choice == 'b' or amt == 0:
                previous_choices["donation"] = 0
                char_animation("You ignore the donation box and continue down the path...")
            
            if choice == 'a' and amt > 0:
                char_animation("PROVIDE INFO 1") #To be added Info 1


            been_in_situations.add(2)

        char_animation("Where do you chose to go?")
        char_animation("1. Back to the clearing")
        char_animation("2. Go to the town")
        choice = get_char_animation_in("Enter your choice: ",{'a':['1','back'],'b':['2','town']}, allow_save=True)
        if choice == 'a':
            situtation = 1
        elif choice == 'b':
            situtation = 10
        
    elif situtation == 3: #Library
        if 3 not in been_in_situations:
            char_animation("\n\nLibrary")
            char_animation("You walk down the path for what seems like ages. You finally reach the library.")
            char_animation("Its a grand structurem, so tall you cant see the top. It so huge you cant see where it ends.")
            char_animation("Yet it appears abandoned, the building is covered in vines.")
            char_animation("You enter the library and see huge lines of bookshelves filled with thousands of dusty books.")
            
            lib_loc = 0
            char_animation("You continue foraward and see two paths, one up a ladder and one down steep stairs.")
            char_animation("Do you: ")
            char_animation("1. Go up the ladder")
            char_animation("2. Go down the stairs")
            choice = get_char_animation_in("Enter your choice: ",{'1':['1','up','ladder'],'-1':['2','down','stairs']},allow_save=True)
            lib_loc += int(choice)
            
            char_animation("You continue foraward and see two more paths, one up a spiral staircase and one down a trapdoor.")
            char_animation("Do you: ")
            char_animation("1. Go up the stairs")
            char_animation("2. Go down the trapdoor")
            choice = get_char_animation_in("Enter your choice: ",{'1':['1','up','stairs'],'-1':['2','down','trapdoor']})
            lib_loc += int(choice)
            if choice == '1':
                person_type += 1
            else:
                person_type -= 1
            
            char_animation("You continue foraward and see two more paths, left towards a large shelf of boooks, same yet different from what you've seen so far or right towards a set of glowing spheres on the bookshelves.")
            char_animation("Do you: ")
            char_animation("1. Go left towards a large shelf of boooks")
            char_animation("2. Go right towards a set of glowing spheres on the bookshelves")
            choice = get_char_animation_in("Enter your choice: ",{'1':['1','left'],'-1':['2','right']})
            if OPENAI_API_KEY != None and choice == '1':
                char_animation("You see open a book and it reads: ")
                char_animation(get_openai_response("Give a short story about an ancient library. Only provide the story do not say anything else."))
            if OPENAI_API_KEY != None and choice == '2':
                char_animation("You see a glowing sphere and you touch it, you see a vision of a great library, the biggest you have ever seen. Inside of it you see you. You hear a voice: ")
                char_animation(get_openai_response("Provide a prophecy of the player doing great things. Only provide the prophecy do not say anything else."))            

            lib_loc += int(choice)
            if choice == '1':
                person_type -= 1
            else:
                person_type += 2


            char_animation("You continue foraward and see two more paths, each with a huge archway and a single word on the top.")
            char_animation("Do you: ")
            char_animation("1. Go left towards the archway with the word 'Power' on the top")
            char_animation("2. Go right towards the archway with the word 'Knowledge' on the top")
            choice = get_char_animation_in("Enter your choice: ",{'1':['1','left'],'-1':['2','right']})
            lib_loc += int(choice)
            if choice == '1':
                morailty -= 2
            if choice == '2':
                morailty += 1
                person_type += 1

            lib_loc //= 2
            
            if lib_loc == 0:
                choice = char_animation_in("Now what?: ")
                if choice == 'BA':
                    char_animation(f".{' '*150}.{' '*150}.{' '*150}\nYou have broken out of the matrix... Just kidding but you can chose either path: ")
                    char_animation("1. Meet the librarian")
                    char_animation("2. Meet the priest")
                    choice = get_char_animation_in("Enter your choice: ",{'a':['1','librarian'],'b':['2','priest']})
                    if choice == 'a':
                        lib_loc = 1
                    elif choice == 'b':
                        person_type += 1
                        lib_loc = -1
                    char_animation("Great choice, also heres +100 Gold for being smart :)")
                else:
                    char_animation(":(")
                    lib_loc = randchoice([-1,1])

            if lib_loc < 0:
                char_animation("You continue down the path and you see a priest, he looks at you with eyes that seem thousands of years old yet like those of a newborn.")
                char_animation(f"He looks at you mysteriously and says: 'Better {' '*150}elsewhere {' '*150}you {' '*150}will {' '*150}do!'")
                char_animation("You feel a tug in your gut and you feel your entire body being compressed into a tiny ball.")
                char_animation("You wake up and are now in...") #Arena
                situtation = 4
                continue
            if lib_loc > 0:
                char_animation("You see a librarian, who looks as old as time itself. She looks at you and says: ")
                char_animation("Its been a long time since I've seen a mortal here... You must be special.")
                char_animation("INFO 1") #To be added info 1
            
            been_in_situations.add(3)
        
        char_animation("Where do you chose to go?")
        char_animation("1. Back to the clearing")
        char_animation("2. Go to the town")
        choice = get_char_animation_in("Enter your choice: ",{'a':['1','back'],'b':['2','town']}, allow_save=True)
        if choice == 'a':
            situtation = 1
        elif choice == 'b':
            situtation = 10

    elif situtation == 4: #Arena
        char_animation("\n\nThe Arena")

    elif situtation == 5: #Dragon's Lair path 1
        person_type -= 1
        char_animation("You go down the dragon lair path, and you see bones scattered along the path. Do you: ")
        char_animation("1. Continue down the path")
        char_animation("2. Go back")
        choice = get_char_animation_in("Enter your choice: ",{'a':['1','continue'],'b':['2','back']}, allow_save=True)
        if choice == 'a':
            situtation = 6
        elif choice == 'b':
            situtation = 1
    
    elif situtation == 6: #Dragon's Lair path 2
        person_type -= 1
        char_animation("You continue down the path, and you see a dead body of a knight, possibly just a few days old, Do you: ")
        char_animation("1. Continue down the path")
        char_animation("2. Go back")
        choice = get_char_animation_in("Enter your choice: ",{'a':['1','continue'],'b':['2','back']}, allow_save=True)
        if choice == 'a':
            situtation = 7
        elif choice == 'b':
            situtation = 1
    
    elif situtation == 7: #Dragon's Lair
        person_type -= 1
        char_animation("You see a large cavern, nothing but darkness ahead. You hear a deep growling sound. Do you: ")
        char_animation("1. Go back")
        char_animation("2. Continue")
        choice = get_char_animation_in("Enter your choice: ",{'a':['1','back'],'b':['2','continue']}, allow_save=True)
        if choice == 'a':
            situtation = 1
        elif choice == 'b':
            situtation = 8
    
    elif situtation == 8: #Dragon's Lair
        if 8 in been_in_situations:
            char_animation("You have already been here before...")
            situtation = 1
            continue
        been_in_situations.add(8)
        char_animation("\n\nDragon's Lair")
        
        char_animation("In the center of the cavern, you can barely see a shadowy figure. You slowly approach it and it moves with deadly speed. In the blink of an eye the way you came in is blocked by rocks.")
        char_animation("In the most petrifying voice you here it speak... Wait its speaking not to you but in you... You can hear its voice in your head.")
        char_animation("It voice loathes of pure evil and it speaks to you.")
        char_animation("\"You can only leave if you answer my riddle correctly.\"")
        riddle = randchoice(list(RIDDLES.keys()))
        char_animation("")
        char_animation("    " + riddle)
        ans = char_animation_in("Answer: ").lower()
        if ans in RIDDLES[riddle]:
            char_animation("The dragon lets out a laugh, yesss you have answer correctly... To bad you still have to die.")
            
        char_animation("The shadowy figure lets out a loud roar and you feel a searing pain in your head.")
        char_animation("You are now... not dead but not alive. You are something worse - a ghost. Not in the mortal plane but not in the afterlife. Neither here nor there")
        career = GHOST
        char_animation("You leave to go back to the clearing...")
        input("")
        situtation = 1

    elif situtation == 10: #Town
        char_animation("\n\nTown")
        char_animation("\n\nThis is all for now! Come back later when chapter 2 is released!")
